export const RECOMMENDATION_SEEDS = [
  {
    name: "opening-setup-priority",
    board: {
      turnCount: 1,
      turn: 1,
      playerGoingFirst: true,
      prizesTakenByPlayer: 0,
      prizesTakenByOpponent: 0,
      hand: ["なかよしポフィン", "博士の研究", "ボスの指令"],
      bench: [],
      active: { cardId: "a1", name: "ヒトカゲ", damage: 0, hp: 70, retreat: 1, energies: 0, isSystem: false, canAttack: false },
      opponentBench: [],
      opponentActive: { cardId: "o1", name: "キチキギスex", damage: 0, hp: 210, retreat: 1, energies: 0, isSystem: true, canAttack: true },
      discard: [],
      deckRemaining: 53,
      availableSupporter: true,
      availableEnergyAttachment: true,
      knownOpponentSwitchOuts: 0,
    },
    expectedPriority: "setup",
  },
  {
    name: "midgame-system-snipe",
    board: {
      turnCount: 5,
      turn: 5,
      playerGoingFirst: true,
      prizesTakenByPlayer: 2,
      prizesTakenByOpponent: 2,
      hand: ["ボスの指令", "ハイパーボール"],
      bench: [{ cardId: "b1", name: "ピジョットex", damage: 0, hp: 280, retreat: 1, energies: 0, isSystem: true, canAttack: false }],
      active: { cardId: "a1", name: "リザードンex", damage: 0, hp: 330, retreat: 2, energies: 3, isSystem: false, canAttack: true },
      opponentBench: [
        { cardId: "o2", name: "イキリンコex", damage: 0, hp: 160, retreat: 2, energies: 0, isSystem: true, canAttack: false },
        { cardId: "o3", name: "ピジョットex", damage: 0, hp: 280, retreat: 1, energies: 0, isSystem: true, canAttack: false }
      ],
      opponentActive: { cardId: "o1", name: "タケルライコex", damage: 100, hp: 240, retreat: 2, energies: 3, isSystem: false, canAttack: true },
      discard: ["ふしぎなアメ"],
      deckRemaining: 31,
      availableSupporter: true,
      availableEnergyAttachment: false,
      knownOpponentSwitchOuts: 1,
    },
    expectedPriority: "system_snipe",
  },
  {
    name: "endgame-finisher",
    board: {
      turnCount: 9,
      turn: 9,
      playerGoingFirst: false,
      prizesTakenByPlayer: 4,
      prizesTakenByOpponent: 4,
      hand: ["ボスの指令", "暗号マニアの解読"],
      bench: [{ cardId: "b1", name: "ピジョットex", damage: 0, hp: 280, retreat: 1, energies: 0, isSystem: true, canAttack: false }],
      active: { cardId: "a1", name: "リザードンex", damage: 0, hp: 330, retreat: 2, energies: 4, isSystem: false, canAttack: true },
      opponentBench: [{ cardId: "o2", name: "イキリンコex", damage: 20, hp: 160, retreat: 2, energies: 0, isSystem: true, canAttack: false }],
      opponentActive: { cardId: "o1", name: "サーナイトex", damage: 110, hp: 310, retreat: 2, energies: 3, isSystem: false, canAttack: true },
      discard: [],
      deckRemaining: 12,
      availableSupporter: true,
      availableEnergyAttachment: false,
      knownOpponentSwitchOuts: 0,
    },
    expectedPriority: "finisher_gust",
  },
];
