export interface PokemonEntry {
  id: number;
  ja: string;
  type: string;
}

// データ量が多いため世代別に定義して統合します
const GEN1: PokemonEntry[] = [
  { id: 1, ja: "フシギダネ", type: "grass" }, { id: 2, ja: "フシギソウ", type: "grass" }, { id: 3, ja: "フシギバナ", type: "grass" },
  { id: 4, ja: "ヒトカゲ", type: "fire" }, { id: 5, ja: "リザード", type: "fire" }, { id: 6, ja: "リザードン", type: "fire" },
  { id: 7, ja: "ゼニガメ", type: "water" }, { id: 8, ja: "カメール", type: "water" }, { id: 9, ja: "カメックス", type: "water" },
  { id: 10, ja: "キャタピー", type: "grass" }, { id: 11, ja: "トランセル", type: "grass" }, { id: 12, ja: "バタフリー", type: "grass" },
  { id: 13, ja: "ビードル", type: "grass" }, { id: 14, ja: "コクーン", type: "grass" }, { id: 15, ja: "スピアー", type: "grass" },
  { id: 16, ja: "ポッポ", type: "colorless" }, { id: 17, ja: "ピジョン", type: "colorless" }, { id: 18, ja: "ピジョット", type: "colorless" },
  { id: 19, ja: "コラッタ", type: "colorless" }, { id: 20, ja: "ラッタ", type: "colorless" }, { id: 21, ja: "オニスズメ", type: "colorless" },
  { id: 22, ja: "オニドリル", type: "colorless" }, { id: 23, ja: "アーボ", type: "psychic" }, { id: 24, ja: "アーボック", type: "psychic" },
  { id: 25, ja: "ピカチュウ", type: "lightning" }, { id: 26, ja: "ライチュウ", type: "lightning" }, { id: 27, ja: "サンド", type: "fighting" },
  { id: 28, ja: "サンドパン", type: "fighting" }, { id: 29, ja: "ニドラン♀", type: "psychic" }, { id: 30, ja: "ニドリーナ", type: "psychic" },
  { id: 31, ja: "ニドクイン", type: "psychic" }, { id: 32, ja: "ニドラン♂", type: "psychic" }, { id: 33, ja: "ニドリーノ", type: "psychic" },
  { id: 34, ja: "ニドキング", type: "psychic" }, { id: 35, ja: "ピッピ", type: "fairy" }, { id: 36, ja: "ピクシー", type: "fairy" },
  { id: 37, ja: "ロコン", type: "fire" }, { id: 38, ja: "キュウコン", type: "fire" }, { id: 39, ja: "プリン", type: "fairy" },
  { id: 40, ja: "プクリン", type: "fairy" }, { id: 41, ja: "ズバット", type: "psychic" }, { id: 42, ja: "ゴルバット", type: "psychic" },
  { id: 43, ja: "ナゾノクサ", type: "grass" }, { id: 44, ja: "クサイハナ", type: "grass" }, { id: 45, ja: "ラフレシア", type: "grass" },
  { id: 46, ja: "パラス", type: "grass" }, { id: 47, ja: "パラセクト", type: "grass" }, { id: 48, ja: "コンパン", type: "grass" },
  { id: 49, ja: "モルフォン", type: "grass" }, { id: 50, ja: "ディグダ", type: "fighting" }, { id: 51, ja: "ダグトリオ", type: "fighting" },
  { id: 52, ja: "ニャース", type: "colorless" }, { id: 53, ja: "ペルシアン", type: "colorless" }, { id: 54, ja: "コダック", type: "water" },
  { id: 55, ja: "ゴルダック", type: "water" }, { id: 56, ja: "マンキー", type: "fighting" }, { id: 57, ja: "オコリザル", type: "fighting" },
  { id: 58, ja: "ガーディ", type: "fire" }, { id: 59, ja: "ウインディ", type: "fire" }, { id: 60, ja: "ニョロモ", type: "water" },
  { id: 61, ja: "ニョロゾ", type: "water" }, { id: 62, ja: "ニョロボン", type: "water" }, { id: 63, ja: "ケーシィ", type: "psychic" },
  { id: 64, ja: "ユンゲラー", type: "psychic" }, { id: 65, ja: "フーディン", type: "psychic" }, { id: 66, ja: "ワンリキー", type: "fighting" },
  { id: 67, ja: "ゴーリキー", type: "fighting" }, { id: 68, ja: "カイリキー", type: "fighting" }, { id: 69, ja: "マダツボミ", type: "grass" },
  { id: 70, ja: "ウツドン", type: "grass" }, { id: 71, ja: "ウツボット", type: "grass" }, { id: 72, ja: "メノクラゲ", type: "water" },
  { id: 73, ja: "ドククラゲ", type: "water" }, { id: 74, ja: "イシツブテ", type: "fighting" }, { id: 75, ja: "ゴローン", type: "fighting" },
  { id: 76, ja: "ゴローニャ", type: "fighting" }, { id: 77, ja: "ポニータ", type: "fire" }, { id: 78, ja: "ギャロップ", type: "fire" },
  { id: 79, ja: "ヤドン", type: "water" }, { id: 80, ja: "ヤドラン", type: "water" }, { id: 81, ja: "コイル", type: "lightning" },
  { id: 82, ja: "レアコイル", type: "lightning" }, { id: 83, ja: "カモネギ", type: "colorless" }, { id: 84, ja: "ドードー", type: "colorless" },
  { id: 85, ja: "ドードリオ", type: "colorless" }, { id: 86, ja: "パウワウ", type: "water" }, { id: 87, ja: "ジュゴン", type: "water" },
  { id: 88, ja: "ベトベター", type: "psychic" }, { id: 89, ja: "ベトベトン", type: "psychic" }, { id: 90, ja: "シェルダー", type: "water" },
  { id: 91, ja: "パルシェン", type: "water" }, { id: 92, ja: "ゴース", type: "psychic" }, { id: 93, ja: "ゴースト", type: "psychic" },
  { id: 94, ja: "ゲンガー", type: "psychic" }, { id: 95, ja: "イワーク", type: "fighting" }, { id: 96, ja: "スリープ", type: "psychic" },
  { id: 97, ja: "スリーパー", type: "psychic" }, { id: 98, ja: "クラブ", type: "water" }, { id: 99, ja: "キングラー", type: "water" },
  { id: 100, ja: "ビリリダマ", type: "lightning" }, { id: 101, ja: "マルマイン", type: "lightning" }, { id: 102, ja: "タマタマ", type: "grass" },
  { id: 103, ja: "ナッシー", type: "grass" }, { id: 104, ja: "カラカラ", type: "fighting" }, { id: 105, ja: "ガラガラ", type: "fighting" },
  { id: 106, ja: "サワムラー", type: "fighting" }, { id: 107, ja: "エビワラー", type: "fighting" }, { id: 108, ja: "ベロリンガ", type: "colorless" },
  { id: 109, ja: "ドガース", type: "psychic" }, { id: 110, ja: "マタドガス", type: "psychic" }, { id: 111, ja: "サイホーン", type: "fighting" },
  { id: 112, ja: "サイドン", type: "fighting" }, { id: 113, ja: "ラッキー", type: "colorless" }, { id: 114, ja: "モンジャラ", type: "grass" },
  { id: 115, ja: "ガルーラ", type: "colorless" }, { id: 116, ja: "タッツー", type: "water" }, { id: 117, ja: "シードラ", type: "water" },
  { id: 118, ja: "トサキント", type: "water" }, { id: 119, ja: "アズマオウ", type: "water" }, { id: 120, ja: "ヒトデマン", type: "water" },
  { id: 121, ja: "スターミー", type: "water" }, { id: 122, ja: "バリヤード", type: "psychic" }, { id: 123, ja: "ストライク", type: "grass" },
  { id: 124, ja: "ルージュラ", type: "water" }, { id: 125, ja: "エレブー", type: "lightning" }, { id: 126, ja: "ブーバー", type: "fire" },
  { id: 127, ja: "カイロス", type: "grass" }, { id: 128, ja: "ケンタロス", type: "colorless" }, { id: 129, ja: "コイキング", type: "water" },
  { id: 130, ja: "ギャラドス", type: "water" }, { id: 131, ja: "ラプラス", type: "water" }, { id: 132, ja: "メタモン", type: "colorless" },
  { id: 133, ja: "イーブイ", type: "colorless" }, { id: 134, ja: "シャワーズ", type: "water" }, { id: 135, ja: "サンダース", type: "lightning" },
  { id: 136, ja: "ブースター", type: "fire" }, { id: 137, ja: "ポリゴン", type: "colorless" }, { id: 138, ja: "オムナイト", type: "water" },
  { id: 139, ja: "オムスター", type: "water" }, { id: 140, ja: "カブト", type: "fighting" }, { id: 141, ja: "カブトプス", type: "fighting" },
  { id: 142, ja: "プテラ", type: "fighting" }, { id: 143, ja: "カビゴン", type: "colorless" }, { id: 144, ja: "フリーザー", type: "water" },
  { id: 145, ja: "サンダー", type: "lightning" }, { id: 146, ja: "ファイヤー", type: "fire" }, { id: 147, ja: "ミニリュウ", type: "dragon" },
  { id: 148, ja: "ハクリュー", type: "dragon" }, { id: 149, ja: "カイリュー", type: "dragon" }, { id: 150, ja: "ミュウツー", type: "psychic" },
  { id: 151, ja: "ミュウ", type: "psychic" },
];

const GEN23: PokemonEntry[] = [
  { id: 152, ja: "チコリータ", type: "grass" }, { id: 153, ja: "ベイリーフ", type: "grass" }, { id: 154, ja: "メガニウム", type: "grass" },
  { id: 155, ja: "ヒノアラシ", type: "fire" }, { id: 156, ja: "マグマラシ", type: "fire" }, { id: 157, ja: "バクフーン", type: "fire" },
  { id: 158, ja: "ワニノコ", type: "water" }, { id: 159, ja: "アリゲイツ", type: "water" }, { id: 160, ja: "オーダイル", type: "water" },
  { id: 161, ja: "オタチ", type: "colorless" }, { id: 162, ja: "オオタチ", type: "colorless" }, { id: 163, ja: "ホーホー", type: "colorless" },
  { id: 164, ja: "ヨルノズク", type: "colorless" }, { id: 165, ja: "レディバ", type: "grass" }, { id: 166, ja: "レディアン", type: "grass" },
  { id: 167, ja: "イトマル", type: "grass" }, { id: 168, ja: "アリアドス", type: "grass" }, { id: 169, ja: "クロバット", type: "psychic" },
  { id: 170, ja: "チョンチー", type: "lightning" }, { id: 171, ja: "ランターン", type: "lightning" }, { id: 172, ja: "ピチュー", type: "lightning" },
  { id: 173, ja: "ピィ", type: "fairy" }, { id: 174, ja: "ププリン", type: "fairy" }, { id: 175, ja: "トゲピー", type: "fairy" },
  { id: 176, ja: "トゲチック", type: "fairy" }, { id: 177, ja: "ネイティ", type: "psychic" }, { id: 178, ja: "ネイティオ", type: "psychic" },
  { id: 179, ja: "メリープ", type: "lightning" }, { id: 180, ja: "モココ", type: "lightning" }, { id: 181, ja: "デンリュウ", type: "lightning" },
  { id: 182, ja: "キレイハナ", type: "grass" }, { id: 183, ja: "マリル", type: "water" }, { id: 184, ja: "マリルリ", type: "water" },
  { id: 185, ja: "ウソッキー", type: "fighting" }, { id: 186, ja: "ニョロトノ", type: "water" }, { id: 187, ja: "ハネッコ", type: "grass" },
  { id: 188, ja: "ポポッコ", type: "grass" }, { id: 189, ja: "ワタッコ", type: "grass" }, { id: 190, ja: "エイパム", type: "colorless" },
  { id: 191, ja: "ヒマナッツ", type: "grass" }, { id: 192, ja: "キマワリ", type: "grass" }, { id: 193, ja: "ヤンヤンマ", type: "grass" },
  { id: 194, ja: "ウパー", type: "water" }, { id: 195, ja: "ヌオー", type: "water" }, { id: 196, ja: "エーフィ", type: "psychic" },
  { id: 197, ja: "ブラッキー", type: "darkness" }, { id: 198, ja: "ヤミカラス", type: "darkness" }, { id: 199, ja: "ヤドキング", type: "water" },
  { id: 200, ja: "ムウマ", type: "psychic" }, { id: 201, ja: "アンノーン", type: "psychic" }, { id: 202, ja: "ソーナンス", type: "psychic" },
  { id: 203, ja: "キリンリキ", type: "psychic" }, { id: 204, ja: "クヌギダマ", type: "grass" }, { id: 205, ja: "フォレトス", type: "metal" },
  { id: 206, ja: "ノコッチ", type: "colorless" }, { id: 207, ja: "グライガー", type: "fighting" }, { id: 208, ja: "ハガネール", type: "metal" },
  { id: 209, ja: "ブルー", type: "fairy" }, { id: 210, ja: "グランブル", type: "fairy" }, { id: 211, ja: "ハリーセン", type: "water" },
  { id: 212, ja: "ハッサム", type: "metal" }, { id: 213, ja: "ツボツボ", type: "grass" }, { id: 214, ja: "ヘラクロス", type: "grass" },
  { id: 215, ja: "ニューラ", type: "darkness" }, { id: 216, ja: "ヒメグマ", type: "colorless" }, { id: 217, ja: "リングマ", type: "colorless" },
  { id: 218, ja: "マグマッグ", type: "fire" }, { id: 219, ja: "マグカルゴ", type: "fire" }, { id: 220, ja: "ウリムー", type: "water" },
  { id: 221, ja: "イノムー", type: "water" }, { id: 222, ja: "サニーゴ", type: "water" }, { id: 223, ja: "テッポウオ", type: "water" },
  { id: 224, ja: "オクタン", type: "water" }, { id: 225, ja: "デリバード", type: "water" }, { id: 226, ja: "マンタイン", type: "water" },
  { id: 227, ja: "エアームド", type: "metal" }, { id: 228, ja: "デルビル", type: "darkness" }, { id: 229, ja: "ヘルガー", type: "darkness" },
  { id: 230, ja: "キングドラ", type: "dragon" }, { id: 231, ja: "ゴマゾウ", type: "fighting" }, { id: 232, ja: "ドンファン", type: "fighting" },
  { id: 233, ja: "ポリゴン２", type: "colorless" }, { id: 234, ja: "オドシシ", type: "colorless" }, { id: 235, ja: "ドーブル", type: "colorless" },
  { id: 236, ja: "バルキー", type: "fighting" }, { id: 237, ja: "カポエラー", type: "fighting" }, { id: 238, ja: "ムチュール", type: "water" },
  { id: 239, ja: "エレキッド", type: "lightning" }, { id: 240, ja: "ブビィ", type: "fire" }, { id: 241, ja: "ミルタンク", type: "colorless" },
  { id: 242, ja: "ハピナス", type: "colorless" }, { id: 243, ja: "ライコウ", type: "lightning" }, { id: 244, ja: "エンテイ", type: "fire" },
  { id: 245, ja: "スイクン", type: "water" }, { id: 246, ja: "ヨーギラス", type: "fighting" }, { id: 247, ja: "サナギラス", type: "fighting" },
  { id: 248, ja: "バンギラス", type: "darkness" }, { id: 249, ja: "ルギア", type: "colorless" }, { id: 250, ja: "ホウオウ", type: "fire" },
  { id: 251, ja: "セレビィ", type: "grass" }, { id: 252, ja: "キモリ", type: "grass" }, { id: 253, ja: "ジュプトル", type: "grass" },
  { id: 254, ja: "ジュカイン", type: "grass" }, { id: 255, ja: "アチャモ", type: "fire" }, { id: 256, ja: "ワカシャモ", type: "fire" },
  { id: 257, ja: "バシャーモ", type: "fire" }, { id: 258, ja: "ミズゴロウ", type: "water" }, { id: 259, ja: "ヌマクロー", type: "water" },
  { id: 260, ja: "ラグラージ", type: "water" }, { id: 261, ja: "ポチエナ", type: "darkness" }, { id: 262, ja: "グラエナ", type: "darkness" },
  { id: 263, ja: "ジグザグマ", type: "colorless" }, { id: 264, ja: "マッスグマ", type: "colorless" }, { id: 265, ja: "ケムッソ", type: "grass" },
  { id: 266, ja: "カラサリス", type: "grass" }, { id: 267, ja: "アゲハント", type: "grass" }, { id: 268, ja: "マユルド", type: "grass" },
  { id: 269, ja: "ドクケイル", type: "grass" }, { id: 270, ja: "ハスボー", type: "water" }, { id: 271, ja: "ハスブレロ", type: "water" },
  { id: 272, ja: "ルンパッパ", type: "water" }, { id: 273, ja: "タネボー", type: "grass" }, { id: 274, ja: "コノハナ", type: "grass" },
  { id: 275, ja: "ダーテング", type: "grass" }, { id: 276, ja: "スバメ", type: "colorless" }, { id: 277, ja: "オオスバメ", type: "colorless" },
  { id: 278, ja: "キャモメ", type: "water" }, { id: 279, ja: "ペリッパー", type: "water" }, { id: 280, ja: "ラルトス", type: "psychic" },
  { id: 281, ja: "キルリア", type: "psychic" }, { id: 282, ja: "サーナイト", type: "psychic" }, { id: 283, ja: "アメタマ", type: "water" },
  { id: 284, ja: "アメモース", type: "water" }, { id: 285, ja: "キノココ", type: "grass" }, { id: 286, ja: "キノガッサ", type: "grass" },
  { id: 287, ja: "ナマケロ", type: "colorless" }, { id: 288, ja: "ヤルキモノ", type: "colorless" }, { id: 289, ja: "ケッキング", type: "colorless" },
  { id: 290, ja: "ツチニン", type: "grass" }, { id: 291, ja: "テッカニン", type: "grass" }, { id: 292, ja: "ヌケニン", type: "psychic" },
  { id: 293, ja: "ゴニョニョ", type: "colorless" }, { id: 294, ja: "ドゴーム", type: "colorless" }, { id: 295, ja: "バクオング", type: "colorless" },
  { id: 296, ja: "マクノシタ", type: "fighting" }, { id: 297, ja: "ハリテヤマ", type: "fighting" }, { id: 298, ja: "ルリリ", type: "fairy" },
  { id: 299, ja: "ノズパス", type: "fighting" }, { id: 300, ja: "エネコ", type: "colorless" }, { id: 301, ja: "エネコロロ", type: "colorless" },
  { id: 302, ja: "ヤミラミ", type: "psychic" }, { id: 303, ja: "クチート", type: "metal" }, { id: 304, ja: "ココドラ", type: "metal" },
  { id: 305, ja: "コドラ", type: "metal" }, { id: 306, ja: "ボスゴドラ", type: "metal" }, { id: 307, ja: "アサナン", type: "fighting" },
  { id: 308, ja: "チャーレム", type: "fighting" }, { id: 309, ja: "ラクライ", type: "lightning" }, { id: 310, ja: "ライボルト", type: "lightning" },
  { id: 311, ja: "プラスル", type: "lightning" }, { id: 312, ja: "マイナン", type: "lightning" }, { id: 313, ja: "バルビート", type: "grass" },
  { id: 314, ja: "イルミーゼ", type: "grass" }, { id: 315, ja: "ロゼリア", type: "grass" }, { id: 316, ja: "ゴクリン", type: "psychic" },
  { id: 317, ja: "マルノーム", type: "psychic" }, { id: 318, ja: "キバニア", type: "water" }, { id: 319, ja: "サメハダー", type: "water" },
  { id: 320, ja: "ホエルコ", type: "water" }, { id: 321, ja: "ホエルオー", type: "water" }, { id: 322, ja: "ドンメル", type: "fire" },
  { id: 323, ja: "バクーダ", type: "fire" }, { id: 324, ja: "コータス", type: "fire" }, { id: 325, ja: "バネブー", type: "psychic" },
  { id: 326, ja: "ブーピッグ", type: "psychic" }, { id: 327, ja: "パッチール", type: "colorless" }, { id: 328, ja: "ナックラー", type: "fighting" },
  { id: 329, ja: "ビブラーバ", type: "dragon" }, { id: 330, ja: "フライゴン", type: "dragon" }, { id: 331, ja: "サボネア", type: "grass" },
  { id: 332, ja: "ノクタス", type: "grass" }, { id: 333, ja: "チルット", type: "colorless" }, { id: 334, ja: "チルタリス", type: "dragon" },
  { id: 335, ja: "ザングース", type: "colorless" }, { id: 336, ja: "ハブネーク", type: "psychic" }, { id: 337, ja: "ルナトーン", type: "psychic" },
  { id: 338, ja: "ソルロック", type: "psychic" }, { id: 339, ja: "ドジョッチ", type: "water" }, { id: 340, ja: "ナマズン", type: "water" },
  { id: 341, ja: "ヘイガニ", type: "water" }, { id: 342, ja: "シザリガー", type: "water" }, { id: 343, ja: "ヤジロン", type: "psychic" },
  { id: 344, ja: "ネンドール", type: "psychic" }, { id: 345, ja: "リリーラ", type: "grass" }, { id: 346, ja: "ユレイドル", type: "grass" },
  { id: 347, ja: "アノプス", type: "water" }, { id: 348, ja: "アーマルド", type: "water" }, { id: 349, ja: "ヒンバス", type: "water" },
  { id: 350, ja: "ミロカロス", type: "water" }, { id: 351, ja: "ポワルン", type: "colorless" }, { id: 352, ja: "カクレオン", type: "colorless" },
  { id: 353, ja: "カゲボウズ", type: "psychic" }, { id: 354, ja: "ジュペッタ", type: "psychic" }, { id: 355, ja: "ヨマワル", type: "psychic" },
  { id: 356, ja: "サマヨール", type: "psychic" }, { id: 357, ja: "トロピウス", type: "grass" }, { id: 358, ja: "チリーン", type: "psychic" },
  { id: 359, ja: "アブソル", type: "darkness" }, { id: 360, ja: "ソーナノ", type: "psychic" }, { id: 361, ja: "ユキワラシ", type: "water" },
  { id: 362, ja: "オニゴーリ", type: "water" }, { id: 363, ja: "タマザラシ", type: "water" }, { id: 364, ja: "トドグラー", type: "water" },
  { id: 365, ja: "トドゼルガ", type: "water" }, { id: 366, ja: "パールル", type: "water" }, { id: 367, ja: "ハンテール", type: "water" },
  { id: 368, ja: "サクラビス", type: "water" }, { id: 369, ja: "ジーランス", type: "water" }, { id: 370, ja: "ラブカス", type: "water" },
  { id: 371, ja: "タツベイ", type: "dragon" }, { id: 372, ja: "コモルー", type: "dragon" }, { id: 373, ja: "ボーマンダ", type: "dragon" },
  { id: 374, ja: "ダンバル", type: "metal" }, { id: 375, ja: "メタング", type: "metal" }, { id: 376, ja: "メタグロス", type: "metal" },
  { id: 377, ja: "レジロック", type: "fighting" }, { id: 378, ja: "レジアイス", type: "water" }, { id: 379, ja: "レジスチル", type: "metal" },
  { id: 380, ja: "ラティアス", type: "dragon" }, { id: 381, ja: "ラティオス", type: "dragon" }, { id: 382, ja: "カイオーガ", type: "water" },
  { id: 383, ja: "グラードン", type: "fighting" }, { id: 384, ja: "レックウザ", type: "dragon" }, { id: 385, ja: "ジラーチ", type: "metal" },
  { id: 386, ja: "デオキシス", type: "psychic" },
];

const GEN45: PokemonEntry[] = [
  { id: 387, ja: "ナエトル", type: "grass" }, { id: 388, ja: "ハヤシガメ", type: "grass" }, { id: 389, ja: "ドダイトス", type: "grass" },
  { id: 390, ja: "ヒコザル", type: "fire" }, { id: 391, ja: "モウカザル", type: "fire" }, { id: 392, ja: "ゴウカザル", type: "fire" },
  { id: 393, ja: "ポッチャマ", type: "water" }, { id: 394, ja: "ポッタイシ", type: "water" }, { id: 395, ja: "エンペルト", type: "water" },
  { id: 396, ja: "ムックル", type: "colorless" }, { id: 397, ja: "ムクバード", type: "colorless" }, { id: 398, ja: "ムクホーク", type: "colorless" },
  { id: 399, ja: "ビッパ", type: "colorless" }, { id: 400, ja: "ビーダル", type: "colorless" }, { id: 401, ja: "コロボーシ", type: "grass" },
  { id: 402, ja: "コロトック", type: "grass" }, { id: 403, ja: "コリンク", type: "lightning" }, { id: 404, ja: "ルクシオ", type: "lightning" },
  { id: 405, ja: "レントラー", type: "lightning" }, { id: 406, ja: "スボミー", type: "grass" }, { id: 407, ja: "ロズレイド", type: "grass" },
  { id: 408, ja: "ズガイドス", type: "fighting" }, { id: 409, ja: "ラムパルド", type: "fighting" }, { id: 410, ja: "タテトプス", type: "metal" },
  { id: 411, ja: "トリデプス", type: "metal" }, { id: 412, ja: "ミノムッチ", type: "grass" }, { id: 413, ja: "ミノマダム", type: "grass" },
  { id: 414, ja: "ガーメイル", type: "grass" }, { id: 415, ja: "ミツハニー", type: "grass" }, { id: 416, ja: "ビークイン", type: "grass" },
  { id: 417, ja: "パチリス", type: "lightning" }, { id: 418, ja: "ブイゼル", type: "water" }, { id: 419, ja: "フローゼル", type: "water" },
  { id: 420, ja: "チェリンボ", type: "grass" }, { id: 421, ja: "チェリム", type: "grass" }, { id: 422, ja: "カラナクシ", type: "water" },
  { id: 423, ja: "トリトドン", type: "water" }, { id: 424, ja: "エツボース", type: "colorless" }, { id: 425, ja: "フワンテ", type: "psychic" },
  { id: 426, ja: "フワライド", type: "psychic" }, { id: 427, ja: "ミミロル", type: "colorless" }, { id: 428, ja: "ミミロップ", type: "colorless" },
  { id: 429, ja: "ムウマージ", type: "psychic" }, { id: 430, ja: "ドンカラス", type: "darkness" }, { id: 431, ja: "ニャルマー", type: "colorless" },
  { id: 432, ja: "ブニャット", type: "colorless" }, { id: 433, ja: "リーシャン", type: "psychic" }, { id: 434, ja: "スカンプー", type: "darkness" },
  { id: 435, ja: "スカタンク", type: "darkness" }, { id: 436, ja: "ドーミラー", type: "metal" }, { id: 437, ja: "ドータクン", type: "metal" },
  { id: 438, ja: "ウソハチ", type: "fighting" }, { id: 439, ja: "マネネ", type: "psychic" }, { id: 440, ja: "ピンプク", type: "colorless" },
  { id: 441, ja: "ペラップ", type: "colorless" }, { id: 442, ja: "ミカルゲ", type: "psychic" }, { id: 443, ja: "フカマル", type: "dragon" },
  { id: 444, ja: "ガバイト", type: "dragon" }, { id: 445, ja: "ガブリアス", type: "dragon" }, { id: 446, ja: "ゴンベ", type: "colorless" },
  { id: 447, ja: "リオル", type: "fighting" }, { id: 448, ja: "ルカリオ", type: "fighting" }, { id: 449, ja: "ヒポポタス", type: "fighting" },
  { id: 450, ja: "カバルドン", type: "fighting" }, { id: 451, ja: "スコルピ", type: "grass" }, { id: 452, ja: "ドラピオン", type: "darkness" },
  { id: 453, ja: "グレッグル", type: "fighting" }, { id: 454, ja: "ドクロッグ", type: "psychic" }, { id: 455, ja: "マスキッパ", type: "grass" },
  { id: 456, ja: "ケイコウオ", type: "water" }, { id: 457, ja: "ネオラント", type: "water" }, { id: 458, ja: "タマンタ", type: "water" },
  { id: 459, ja: "ユキカブリ", type: "grass" }, { id: 460, ja: "ユキノオー", type: "grass" }, { id: 461, ja: "マニューラ", type: "darkness" },
  { id: 462, ja: "ジバコイル", type: "lightning" }, { id: 463, ja: "ベロベルト", type: "colorless" }, { id: 464, ja: "ドサイドン", type: "fighting" },
  { id: 465, ja: "モジャンボ", type: "grass" }, { id: 466, ja: "エレキブル", type: "lightning" }, { id: 467, ja: "ブーバーン", type: "fire" },
  { id: 468, ja: "トゲキッス", type: "fairy" }, { id: 469, ja: "メガヤンマ", type: "grass" }, { id: 470, ja: "リーフィア", type: "grass" },
  { id: 471, ja: "グレイシア", type: "water" }, { id: 472, ja: "グライオン", type: "fighting" }, { id: 473, ja: "マンムー", type: "water" },
  { id: 474, ja: "ポリゴンＺ", type: "colorless" }, { id: 475, ja: "エルレイド", type: "psychic" }, { id: 476, ja: "ダイノーズ", type: "fighting" },
  { id: 477, ja: "ヨノワール", type: "psychic" }, { id: 478, ja: "ユキメノコ", type: "water" }, { id: 479, ja: "ロトム", type: "lightning" },
  { id: 480, ja: "ユクシー", type: "psychic" }, { id: 481, ja: "エムリット", type: "psychic" }, { id: 482, ja: "アグノム", type: "psychic" },
  { id: 483, ja: "ディアルガ", type: "metal" }, { id: 484, ja: "パルキア", type: "dragon" }, { id: 485, ja: "ヒードラン", type: "fire" },
  { id: 486, ja: "レジギガス", type: "colorless" }, { id: 487, ja: "ギラティナ", type: "psychic" }, { id: 488, ja: "クレセリア", type: "psychic" },
  { id: 489, ja: "フィオネ", type: "water" }, { id: 490, ja: "マナフィ", type: "water" }, { id: 491, ja: "ダークライ", type: "darkness" },
  { id: 492, ja: "シェイミ", type: "grass" }, { id: 493, ja: "アルセウス", type: "colorless" }, { id: 494, ja: "ビクティニ", type: "fire" },
  { id: 495, ja: "ツタージャ", type: "grass" }, { id: 496, ja: "ジャノビー", type: "grass" }, { id: 497, ja: "ジャローダ", type: "grass" },
  { id: 498, ja: "ポカブ", type: "fire" }, { id: 499, ja: "チャオブー", type: "fire" }, { id: 500, ja: "エンブオー", type: "fire" },
  { id: 501, ja: "ミジュマル", type: "water" }, { id: 502, ja: "フタチマル", type: "water" }, { id: 503, ja: "ダイケンキ", type: "water" },
  { id: 504, ja: "ミネズミ", type: "colorless" }, { id: 505, ja: "ミルホッグ", type: "colorless" }, { id: 506, ja: "ヨーテリー", type: "colorless" },
  { id: 507, ja: "ハーデリア", type: "colorless" }, { id: 508, ja: "ムーランド", type: "colorless" }, { id: 509, ja: "チョロネコ", type: "darkness" },
  { id: 510, ja: "レパルダス", type: "darkness" }, { id: 511, ja: "ヤナップ", type: "grass" }, { id: 512, ja: "ヤナッキー", type: "grass" },
  { id: 513, ja: "バオップ", type: "fire" }, { id: 514, ja: "バオッキー", type: "fire" }, { id: 515, ja: "ヒヤップ", type: "water" },
  { id: 516, ja: "ヒヤッキー", type: "water" }, { id: 517, ja: "ムンナ", type: "psychic" }, { id: 518, ja: "ムシャーナ", type: "psychic" },
  { id: 519, ja: "マメパト", type: "colorless" }, { id: 520, ja: "ハトーボー", type: "colorless" }, { id: 521, ja: "ケンホロウ", type: "colorless" },
  { id: 522, ja: "シママ", type: "lightning" }, { id: 523, ja: "ゼブライカ", type: "lightning" }, { id: 524, ja: "ダンゴロ", type: "fighting" },
  { id: 525, ja: "ガントル", type: "fighting" }, { id: 526, ja: "ギガイアス", type: "fighting" }, { id: 527, ja: "コロモリ", type: "psychic" },
  { id: 528, ja: "ココロモリ", type: "psychic" }, { id: 529, ja: "モグリュー", type: "fighting" }, { id: 530, ja: "ドリュウズ", type: "metal" },
  { id: 531, ja: "タブンネ", type: "colorless" }, { id: 532, ja: "ドッコラー", type: "fighting" }, { id: 533, ja: "ドテッコツ", type: "fighting" },
  { id: 534, ja: "ローブシン", type: "fighting" }, { id: 535, ja: "オタマロ", type: "water" }, { id: 536, ja: "ガマガル", type: "water" },
  { id: 537, ja: "ガマゲロゲ", type: "water" }, { id: 538, ja: "ナゲキ", type: "fighting" }, { id: 539, ja: "ダゲキ", type: "fighting" },
  { id: 540, ja: "クルミル", type: "grass" }, { id: 541, ja: "クルマユ", type: "grass" }, { id: 542, ja: "ハハコモリ", type: "grass" },
  { id: 543, ja: "フシデ", type: "psychic" }, { id: 544, ja: "ホイーガ", type: "psychic" }, { id: 545, ja: "ペンドラー", type: "psychic" },
  { id: 546, ja: "モンメン", type: "fairy" }, { id: 547, ja: "エルフーン", type: "fairy" }, { id: 548, ja: "チュリネ", type: "grass" },
  { id: 549, ja: "ドレディア", type: "grass" }, { id: 550, ja: "バスラオ", type: "water" }, { id: 551, ja: "メグロコ", type: "fighting" },
  { id: 552, ja: "ワルビル", type: "fighting" }, { id: 553, ja: "ワルビアル", type: "darkness" }, { id: 554, ja: "ダルマッカ", type: "fire" },
  { id: 555, ja: "ヒヒダルマ", type: "fire" }, { id: 556, ja: "マラカッチ", type: "grass" }, { id: 557, ja: "イシズマイ", type: "fighting" },
  { id: 558, ja: "イワパレス", type: "fighting" }, { id: 559, ja: "ズルッグ", type: "darkness" }, { id: 560, ja: "ズルズキン", type: "darkness" },
  { id: 561, ja: "シンボラー", type: "psychic" }, { id: 562, ja: "デスマス", type: "psychic" }, { id: 563, ja: "デスカーン", type: "psychic" },
  { id: 564, ja: "プロトーガ", type: "water" }, { id: 565, ja: "アバゴーラ", type: "water" }, { id: 566, ja: "アーケン", type: "fighting" },
  { id: 567, ja: "アーケオス", type: "fighting" }, { id: 568, ja: "ヤブクロン", type: "psychic" }, { id: 569, ja: "ダストダス", type: "psychic" },
  { id: 570, ja: "ゾロア", type: "darkness" }, { id: 571, ja: "ゾロアーク", type: "darkness" }, { id: 572, ja: "チラーミィ", type: "colorless" },
  { id: 573, ja: "チラチーノ", type: "colorless" }, { id: 574, ja: "ゴチム", type: "psychic" }, { id: 575, ja: "ゴチミル", type: "psychic" },
  { id: 576, ja: "ゴチルゼル", type: "psychic" }, { id: 577, ja: "ユニラン", type: "psychic" }, { id: 578, ja: "ダブラン", type: "psychic" },
  { id: 579, ja: "ランクルス", type: "psychic" }, { id: 580, ja: "コアルヒー", type: "water" }, { id: 581, ja: "スワンナ", type: "water" },
  { id: 582, ja: "バニプッチ", type: "water" }, { id: 583, ja: "バニリッチ", type: "water" }, { id: 584, ja: "バイバニラ", type: "water" },
  { id: 585, ja: "シキジカ", type: "colorless" }, { id: 586, ja: "メブキジカ", type: "colorless" }, { id: 587, ja: "エモンガ", type: "lightning" },
  { id: 588, ja: "カブルモ", type: "grass" }, { id: 589, ja: "シュバルゴ", type: "metal" }, { id: 590, ja: "タマゲタケ", type: "grass" },
  { id: 591, ja: "モロバレル", type: "grass" }, { id: 592, ja: "プルリル", type: "water" }, { id: 593, ja: "ブルンゲル", type: "water" },
  { id: 594, ja: "ママンボウ", type: "water" }, { id: 595, ja: "バチュル", type: "lightning" }, { id: 596, ja: "デンチュラ", type: "lightning" },
  { id: 597, ja: "テッシード", type: "metal" }, { id: 598, ja: "ナットレイ", type: "metal" }, { id: 599, ja: "ギアル", type: "metal" },
  { id: 600, ja: "ギギアル", type: "metal" }, { id: 601, ja: "ギギギアル", type: "metal" }, { id: 602, ja: "シビシラス", type: "lightning" },
  { id: 603, ja: "シビビール", type: "lightning" }, { id: 604, ja: "シビルドン", type: "lightning" }, { id: 605, ja: "リグレー", type: "psychic" },
  { id: 606, ja: "オーベム", type: "psychic" }, { id: 607, ja: "ヒトモシ", type: "fire" }, { id: 608, ja: "ランプラー", type: "fire" },
  { id: 609, ja: "シャンデラ", type: "fire" }, { id: 610, ja: "キバゴ", type: "dragon" }, { id: 611, ja: "オノンド", type: "dragon" },
  { id: 612, ja: "オノノクス", type: "dragon" }, { id: 613, ja: "クマシュン", type: "water" }, { id: 614, ja: "ツンベアー", type: "water" },
  { id: 615, ja: "フリージオ", type: "water" }, { id: 616, ja: "チョボマキ", type: "grass" }, { id: 617, ja: "アギルダー", type: "grass" },
  { id: 618, ja: "マッギョ", type: "fighting" }, { id: 619, ja: "コジョフー", type: "fighting" }, { id: 620, ja: "コジョンド", type: "fighting" },
  { id: 621, ja: "クリムガン", type: "dragon" }, { id: 622, ja: "ゴビット", type: "psychic" }, { id: 623, ja: "ゴルーグ", type: "psychic" },
  { id: 624, ja: "コマタナ", type: "metal" }, { id: 625, ja: "キリキザン", type: "metal" }, { id: 626, ja: "バッフロン", type: "colorless" },
  { id: 627, ja: "ワシボン", type: "colorless" }, { id: 628, ja: "ウォーグル", type: "colorless" }, { id: 629, ja: "バルチャイ", type: "darkness" },
  { id: 630, ja: "バルジーナ", type: "darkness" }, { id: 631, ja: "クイタラン", type: "fire" }, { id: 632, ja: "アイアント", type: "metal" },
  { id: 633, ja: "モノズ", type: "darkness" }, { id: 634, ja: "ジヘッド", type: "darkness" }, { id: 635, ja: "サザンドラ", type: "darkness" },
  { id: 636, ja: "メラルバ", type: "fire" }, { id: 637, ja: "ウルガモス", type: "fire" }, { id: 638, ja: "コバルオン", type: "metal" },
  { id: 639, ja: "テラキオン", type: "fighting" }, { id: 640, ja: "ビリジオン", type: "grass" }, { id: 641, ja: "トルネロス", type: "colorless" },
  { id: 642, ja: "ボルトロス", type: "lightning" }, { id: 643, ja: "レシラム", type: "fire" }, { id: 644, ja: "ゼクロム", type: "lightning" },
  { id: 645, ja: "ランドロス", type: "fighting" }, { id: 646, ja: "キュレム", type: "water" }, { id: 647, ja: "ケルディオ", type: "water" },
  { id: 648, ja: "メロエッタ", type: "psychic" }, { id: 649, ja: "ゲノセクト", type: "metal" },
];

const GEN69: PokemonEntry[] = [
  { id: 650, ja: "ハリマロン", type: "grass" }, { id: 651, ja: "ハリボーグ", type: "grass" }, { id: 652, ja: "ブリガロン", type: "grass" },
  { id: 653, ja: "フォッコ", type: "fire" }, { id: 654, ja: "テールナー", type: "fire" }, { id: 655, ja: "マフォクシー", type: "fire" },
  { id: 656, ja: "ケロマツ", type: "water" }, { id: 657, ja: "ゲコガシラ", type: "water" }, { id: 658, ja: "ゲッコウガ", type: "water" },
  { id: 659, ja: "ホルビー", type: "colorless" }, { id: 660, ja: "ホルード", type: "colorless" }, { id: 661, ja: "ヤヤコマ", type: "colorless" },
  { id: 662, ja: "ヒノヤコマ", type: "fire" }, { id: 663, ja: "ファイアロー", type: "fire" }, { id: 664, ja: "コフキムシ", type: "grass" },
  { id: 665, ja: "コフーライ", type: "grass" }, { id: 666, ja: "ビビヨン", type: "grass" }, { id: 667, ja: "シシコ", type: "fire" },
  { id: 668, ja: "カエンジシ", type: "fire" }, { id: 669, ja: "フラベベ", type: "fairy" }, { id: 670, ja: "フラエッテ", type: "fairy" },
  { id: 671, ja: "フラージェス", type: "fairy" }, { id: 672, ja: "メェークル", type: "grass" }, { id: 673, ja: "ゴーゴート", type: "grass" },
  { id: 674, ja: "ヤンチャム", type: "fighting" }, { id: 675, ja: "ゴロンダ", type: "darkness" }, { id: 676, ja: "トリミアン", type: "colorless" },
  { id: 677, ja: "ニャスパー", type: "psychic" }, { id: 678, ja: "ニャオニクス", type: "psychic" }, { id: 679, ja: "ヒトツキ", type: "metal" },
  { id: 680, ja: "ニダンギル", type: "metal" }, { id: 681, ja: "ギルガルド", type: "metal" }, { id: 682, ja: "シュシュプ", type: "fairy" },
  { id: 683, ja: "フレフワン", type: "fairy" }, { id: 684, ja: "ペロッパフ", type: "fairy" }, { id: 685, ja: "ペロリーム", type: "fairy" },
  { id: 686, ja: "マーイーカ", type: "darkness" }, { id: 687, ja: "カラマネロ", type: "darkness" }, { id: 688, ja: "カメテテ", type: "fighting" },
  { id: 689, ja: "ガメノデス", type: "fighting" }, { id: 690, ja: "クズモー", type: "psychic" }, { id: 691, ja: "ドラミドロ", type: "dragon" },
  { id: 692, ja: "ウデッポウ", type: "water" }, { id: 693, ja: "ブロスター", type: "water" }, { id: 694, ja: "エリキテル", type: "lightning" },
  { id: 695, ja: "エレザード", type: "lightning" }, { id: 696, ja: "チゴラス", type: "dragon" }, { id: 697, ja: "ガチゴラス", type: "dragon" },
  { id: 698, ja: "アマルス", type: "water" }, { id: 699, ja: "アマルルガ", type: "water" }, { id: 700, ja: "ニンフィア", type: "fairy" },
  { id: 701, ja: "ルチャブル", type: "fighting" }, { id: 702, ja: "デデンネ", type: "lightning" }, { id: 703, ja: "メレシー", type: "psychic" },
  { id: 704, ja: "ヌメラ", type: "dragon" }, { id: 705, ja: "ヌメイル", type: "dragon" }, { id: 706, ja: "ヌメルゴン", type: "dragon" },
  { id: 707, ja: "クレッフィ", type: "metal" }, { id: 708, ja: "ボクレー", type: "grass" }, { id: 709, ja: "オーロット", type: "grass" },
  { id: 710, ja: "バケッチャ", type: "psychic" }, { id: 711, ja: "パンプジン", type: "psychic" }, { id: 712, ja: "カチコール", type: "water" },
  { id: 713, ja: "クレベース", type: "water" }, { id: 714, ja: "オンバット", type: "psychic" }, { id: 715, ja: "オンバーン", type: "psychic" },
  { id: 716, ja: "ゼルネアス", type: "fairy" }, { id: 717, ja: "イベルタル", type: "darkness" }, { id: 718, ja: "ジガルデ", type: "dragon" },
  { id: 719, ja: "ディアンシー", type: "fairy" }, { id: 720, ja: "フーパ", type: "psychic" }, { id: 721, ja: "ボルケニオン", type: "fire" },
  { id: 722, ja: "モクロー", type: "grass" }, { id: 723, ja: "フクスロー", type: "grass" }, { id: 724, ja: "ジュナイパー", type: "grass" },
  { id: 725, ja: "ニャビー", type: "fire" }, { id: 726, ja: "ニャヒート", type: "fire" }, { id: 727, ja: "ガオガエン", type: "fire" },
  { id: 728, ja: "アシマリ", type: "water" }, { id: 729, ja: "オシャマリ", type: "water" }, { id: 730, ja: "アシレーヌ", type: "water" },
  { id: 731, ja: "ツツケラ", type: "colorless" }, { id: 732, ja: "ケララッパ", type: "colorless" }, { id: 733, ja: "ドデカバシ", type: "colorless" },
  { id: 734, ja: "ヤングース", type: "colorless" }, { id: 735, ja: "デカグース", type: "colorless" }, { id: 736, ja: "アゴジムシ", type: "grass" },
  { id: 737, ja: "デンヂムシ", type: "lightning" }, { id: 738, ja: "クワガノン", type: "lightning" }, { id: 739, ja: "マケンカニ", type: "fighting" },
  { id: 740, ja: "ケケンカニ", type: "fighting" }, { id: 741, ja: "オドリドリ", type: "fire" }, { id: 742, ja: "アブリー", type: "fairy" },
  { id: 743, ja: "アブリボン", type: "fairy" }, { id: 744, ja: "イワンコ", type: "fighting" }, { id: 745, ja: "ルガルガン", type: "fighting" },
  { id: 746, ja: "ヨワシ", type: "water" }, { id: 747, ja: "ヒドイデ", type: "psychic" }, { id: 748, ja: "ドヒドイデ", type: "psychic" },
  { id: 749, ja: "ドロバンコ", type: "fighting" }, { id: 750, ja: "バンバドロ", type: "fighting" }, { id: 751, ja: "シズクモ", type: "water" },
  { id: 752, ja: "オニシズクモ", type: "water" }, { id: 753, ja: "カリキリ", type: "grass" }, { id: 754, ja: "ラランテス", type: "grass" },
  { id: 755, ja: "ネマシュ", type: "grass" }, { id: 756, ja: "マシェード", type: "grass" }, { id: 757, ja: "ヤトウモリ", type: "fire" },
  { id: 758, ja: "エンニュート", type: "fire" }, { id: 759, ja: "ヌイコグマ", type: "colorless" }, { id: 760, ja: "キテルグマ", type: "fighting" },
  { id: 761, ja: "アマカジ", type: "grass" }, { id: 762, ja: "アママイコ", type: "grass" }, { id: 763, ja: "アマージョ", type: "grass" },
  { id: 764, ja: "キュワワー", type: "fairy" }, { id: 765, ja: "ヤレユータン", type: "colorless" }, { id: 766, ja: "ナゲツケサル", type: "fighting" },
  { id: 767, ja: "コソクムシ", type: "water" }, { id: 768, ja: "グソクムシャ", type: "water" }, { id: 769, ja: "スナバァ", type: "fighting" },
  { id: 770, ja: "シロデスナ", type: "fighting" }, { id: 771, ja: "ナマコブシ", type: "water" }, { id: 772, ja: "タイプ：ヌル", type: "colorless" },
  { id: 773, ja: "シルヴァディ", type: "colorless" }, { id: 774, ja: "メテノ", type: "fighting" }, { id: 775, ja: "ネッコアラ", type: "colorless" },
  { id: 776, ja: "バクガメス", type: "fire" }, { id: 777, ja: "トゲデマル", type: "lightning" }, { id: 778, ja: "ミミッキュ", type: "psychic" },
  { id: 779, ja: "ハギギシリ", type: "psychic" }, { id: 780, ja: "ジジーロン", type: "dragon" }, { id: 781, ja: "ダダリン", type: "grass" },
  { id: 782, ja: "ジャラコ", type: "dragon" }, { id: 783, ja: "ジャランゴ", type: "dragon" }, { id: 784, ja: "ジャラランガ", type: "dragon" },
  { id: 785, ja: "カプ・コケコ", type: "lightning" }, { id: 786, ja: "カプ・テテフ", type: "psychic" }, { id: 787, ja: "カプ・ブルル", type: "grass" },
  { id: 788, ja: "カプ・レヒレ", type: "water" }, { id: 789, ja: "コスモッグ", type: "psychic" }, { id: 790, ja: "コスモウム", type: "psychic" },
  { id: 791, ja: "ソルガレオ", type: "metal" }, { id: 792, ja: "ルナアーラ", type: "psychic" }, { id: 793, ja: "ウツロイド", type: "psychic" },
  { id: 794, ja: "マッシブーン", type: "fighting" }, { id: 795, ja: "フェローチェ", type: "grass" }, { id: 796, ja: "デンジュモク", type: "lightning" },
  { id: 797, ja: "テッカグヤ", type: "metal" }, { id: 798, ja: "カミツルギ", type: "grass" }, { id: 799, ja: "アクジキング", type: "darkness" },
  { id: 800, ja: "ネクロズマ", type: "psychic" }, { id: 801, ja: "マギアナ", type: "metal" }, { id: 802, ja: "マーシャドー", type: "psychic" },
  { id: 803, ja: "ベベノム", type: "psychic" }, { id: 804, ja: "アーゴヨン", type: "psychic" }, { id: 805, ja: "ツンデツンデ", type: "metal" },
  { id: 806, ja: "ズガドーン", type: "fire" }, { id: 807, ja: "ゼラオラ", type: "lightning" }, { id: 808, ja: "メルタン", type: "metal" },
  { id: 809, ja: "メルメタル", type: "metal" }, { id: 810, ja: "サルノリ", type: "grass" }, { id: 811, ja: "バチンキー", type: "grass" },
  { id: 812, ja: "ゴリランダー", type: "grass" }, { id: 813, ja: "ヒバニー", type: "fire" }, { id: 814, ja: "ラビフット", type: "fire" },
  { id: 815, ja: "エースバーン", type: "fire" }, { id: 816, ja: "メッソン", type: "water" }, { id: 817, ja: "ジメレオン", type: "water" },
  { id: 818, ja: "インテレオン", type: "water" }, { id: 819, ja: "ホシガリス", type: "colorless" }, { id: 820, ja: "ヨクバリス", type: "colorless" },
  { id: 821, ja: "ココガラ", type: "colorless" }, { id: 822, ja: "アオガラス", type: "colorless" }, { id: 823, ja: "アーマーガア", type: "metal" },
  { id: 824, ja: "サッチムシ", type: "grass" }, { id: 825, ja: "レドームシ", type: "grass" }, { id: 826, ja: "イオルブ", type: "psychic" },
  { id: 827, ja: "クスネ", type: "darkness" }, { id: 828, ja: "フォクスライ", type: "darkness" }, { id: 829, ja: "ヒメンカ", type: "grass" },
  { id: 830, ja: "ワタシラガ", type: "grass" }, { id: 831, ja: "ウールー", type: "colorless" }, { id: 832, ja: "バイウールー", type: "colorless" },
  { id: 833, ja: "カムカメ", type: "water" }, { id: 834, ja: "カジリガメ", type: "water" }, { id: 835, ja: "ワンパチ", type: "lightning" },
  { id: 836, ja: "パルスワン", type: "lightning" }, { id: 837, ja: "タンドン", type: "fighting" }, { id: 838, ja: "トロッゴン", type: "fire" },
  { id: 839, ja: "セキタンザン", type: "fire" }, { id: 840, ja: "カジッチュ", type: "grass" }, { id: 841, ja: "アップリュー", type: "dragon" },
  { id: 842, ja: "タルップル", type: "dragon" }, { id: 843, ja: "スナヘビ", type: "fighting" }, { id: 844, ja: "サダイジャ", type: "fighting" },
  { id: 845, ja: "ウッウ", type: "water" }, { id: 846, ja: "サシカマス", type: "water" }, { id: 847, ja: "カマスジョー", type: "water" },
  { id: 848, ja: "エレズン", type: "lightning" }, { id: 849, ja: "ストリンダー", type: "lightning" }, { id: 850, ja: "ヤクデ", type: "fire" },
  { id: 851, ja: "マルヤクデ", type: "fire" }, { id: 852, ja: "タタッコ", type: "fighting" }, { id: 853, ja: "オトスパス", type: "fighting" },
  { id: 854, ja: "ヤバチャ", type: "psychic" }, { id: 855, ja: "ポットデス", type: "psychic" }, { id: 856, ja: "ミブリム", type: "psychic" },
  { id: 857, ja: "テブリム", type: "psychic" }, { id: 858, ja: "ブリムオン", type: "psychic" }, { id: 859, ja: "ベロバー", type: "darkness" },
  { id: 860, ja: "ギモー", type: "darkness" }, { id: 861, ja: "オーロンゲ", type: "darkness" }, { id: 862, ja: "タチフサグマ", type: "darkness" },
  { id: 863, ja: "ニャイキング", type: "metal" }, { id: 864, ja: "サニゴーン", type: "psychic" }, { id: 865, ja: "ネギガナイト", type: "fighting" },
  { id: 866, ja: "バリコオル", type: "psychic" }, { id: 867, ja: "デスバーン", type: "fighting" }, { id: 868, ja: "マホミル", type: "fairy" },
  { id: 869, ja: "マホイップ", type: "fairy" }, { id: 870, ja: "タイレーツ", type: "fighting" }, { id: 871, ja: "バチンウニ", type: "lightning" },
  { id: 872, ja: "ユキハミ", type: "water" }, { id: 873, ja: "モスノウ", type: "water" }, { id: 874, ja: "イシヘンジン", type: "fighting" },
  { id: 875, ja: "コオリッポ", type: "water" }, { id: 876, ja: "イエッサン", type: "psychic" }, { id: 877, ja: "モルペコ", type: "lightning" },
  { id: 878, ja: "ゾウドウ", type: "metal" }, { id: 879, ja: "ダイオウドウ", type: "metal" }, { id: 880, ja: "パッチラゴン", type: "lightning" },
  { id: 881, ja: "パッチルドン", type: "water" }, { id: 882, ja: "ウオノラゴン", type: "water" }, { id: 883, ja: "ウオチルドン", type: "water" },
  { id: 884, ja: "ジュラルドン", type: "metal" }, { id: 885, ja: "ドラメシヤ", type: "psychic" }, { id: 886, ja: "ドロンチ", type: "psychic" },
  { id: 887, ja: "ドラパルト", type: "psychic" }, { id: 888, ja: "ザシアン", type: "metal" }, { id: 889, ja: "ザマゼンタ", type: "fighting" },
  { id: 890, ja: "ムゲンダイナ", type: "dragon" }, { id: 891, ja: "ダクマ", type: "fighting" }, { id: 892, ja: "ウーラオス", type: "fighting" },
  { id: 893, ja: "ザルード", type: "grass" }, { id: 894, ja: "レジエレキ", type: "lightning" }, { id: 895, ja: "レジドラゴ", type: "dragon" },
  { id: 896, ja: "ブリザポス", type: "water" }, { id: 897, ja: "レイスポス", type: "psychic" }, { id: 898, ja: "バドレックス", type: "psychic" },
  { id: 899, ja: "アヤシシ", type: "colorless" }, { id: 900, ja: "バサギリ", type: "fighting" }, { id: 901, ja: "ガチグマ", type: "fighting" },
  { id: 902, ja: "イダイトウ", type: "water" }, { id: 903, ja: "オオニューラ", type: "fighting" }, { id: 904, ja: "ハリーマン", type: "darkness" },
  { id: 905, ja: "ラブトロス", type: "fairy" }, { id: 906, ja: "ニャオハ", type: "grass" }, { id: 907, ja: "ニャローテ", type: "grass" },
  { id: 908, ja: "マスカーニャ", type: "grass" }, { id: 909, ja: "ホゲータ", type: "fire" }, { id: 910, ja: "アチゲータ", type: "fire" },
  { id: 911, ja: "ラウドボーン", type: "fire" }, { id: 912, ja: "クワッス", type: "water" }, { id: 913, ja: "ウェルカモ", type: "water" },
  { id: 914, ja: "ウェーニバル", type: "water" }, { id: 915, ja: "グルトン", type: "colorless" }, { id: 916, ja: "パフュートン", type: "colorless" },
  { id: 917, ja: "タマンチュラ", type: "grass" }, { id: 918, ja: "ワナイダー", type: "grass" }, { id: 919, ja: "マメバッタ", type: "grass" },
  { id: 920, ja: "エクスレッグ", type: "grass" }, { id: 921, ja: "パモ", type: "lightning" }, { id: 922, ja: "パモット", type: "lightning" },
  { id: 923, ja: "パーモット", type: "lightning" }, { id: 924, ja: "ワッカネズミ", type: "colorless" }, { id: 925, ja: "イッカネズミ", type: "colorless" },
  { id: 926, ja: "パピモッチ", type: "fairy" }, { id: 927, ja: "バウッツェル", type: "fairy" }, { id: 928, ja: "ミニーブ", type: "grass" },
  { id: 929, ja: "オリーニョ", type: "grass" }, { id: 930, ja: "オリーヴァ", type: "grass" }, { id: 931, ja: "イキリンコ", type: "colorless" },
  { id: 932, ja: "コジオ", type: "fighting" }, { id: 933, ja: "ジオヅム", type: "fighting" }, { id: 934, ja: "キョジオーン", type: "fighting" },
  { id: 935, ja: "カルボウ", type: "fire" }, { id: 936, ja: "グレンアルマ", type: "fire" }, { id: 937, ja: "ソウブレイズ", type: "fire" },
  { id: 938, ja: "ズピカ", type: "lightning" }, { id: 939, ja: "ハラバリー", type: "lightning" }, { id: 940, ja: "カイデン", type: "lightning" },
  { id: 941, ja: "タイカイデン", type: "lightning" }, { id: 942, ja: "オラチフ", type: "darkness" }, { id: 943, ja: "マフィティフ", type: "darkness" },
  { id: 944, ja: "シルシュルー", type: "psychic" }, { id: 945, ja: "タギングル", type: "psychic" }, { id: 946, ja: "アノクサ", type: "grass" },
  { id: 947, ja: "アノホラグサ", type: "grass" }, { id: 948, ja: "ノノクラゲ", type: "grass" }, { id: 949, ja: "リククラゲ", type: "grass" },
  { id: 950, ja: "ガケガニ", type: "fighting" }, { id: 951, ja: "カプサイジ", type: "grass" }, { id: 952, ja: "スコヴィラン", type: "grass" },
  { id: 953, ja: "シガロコ", type: "grass" }, { id: 954, ja: "ベラカス", type: "psychic" }, { id: 955, ja: "ヒラヒナ", type: "psychic" },
  { id: 956, ja: "クエスパトラ", type: "psychic" }, { id: 957, ja: "カヌチャン", type: "metal" }, { id: 958, ja: "ナカヌチャン", type: "metal" },
  { id: 959, ja: "デカヌチャン", type: "metal" }, { id: 960, ja: "ウミディグダ", type: "water" }, { id: 961, ja: "ウミトリオ", type: "water" },
  { id: 962, ja: "オトシドリ", type: "darkness" }, { id: 963, ja: "ナミイルカ", type: "water" }, { id: 964, ja: "イルカマン", type: "water" },
  { id: 965, ja: "ブロロン", type: "metal" }, { id: 966, ja: "ブロロローム", type: "metal" }, { id: 967, ja: "モトトカゲ", type: "dragon" },
  { id: 968, ja: "ミミズズ", type: "metal" }, { id: 969, ja: "キラーメ", type: "fighting" }, { id: 970, ja: "キラフロル", type: "fighting" },
  { id: 971, ja: "ボチ", type: "psychic" }, { id: 972, ja: "ハカドッグ", type: "psychic" }, { id: 973, ja: "カラミンゴ", type: "fighting" },
  { id: 974, ja: "アルクジラ", type: "water" }, { id: 975, ja: "ハルクジラ", type: "water" }, { id: 976, ja: "ミガルーサ", type: "water" },
  { id: 977, ja: "ヘイラッシャ", type: "water" }, { id: 978, ja: "シャリタツ", type: "water" }, { id: 979, ja: "コノヨザル", type: "fighting" },
  { id: 980, ja: "ドオー", type: "darkness" }, { id: 981, ja: "リキキリン", type: "psychic" }, { id: 982, ja: "ノココッチ", type: "colorless" },
  { id: 983, ja: "ドドゲザン", type: "metal" }, { id: 984, ja: "イダイナキバ", type: "fighting" }, { id: 985, ja: "サケブシッポ", type: "psychic" },
  { id: 986, ja: "アラブルタケ", type: "grass" }, { id: 987, ja: "ハバタクカミ", type: "psychic" }, { id: 988, ja: "チヲハウハネ", type: "fighting" },
  { id: 989, ja: "スナノケガワ", type: "lightning" }, { id: 990, ja: "テツノワダチ", type: "metal" }, { id: 991, ja: "テツノツツミ", type: "water" },
  { id: 992, ja: "テツノドクガ", type: "fire" }, { id: 993, ja: "テツノイバラ", type: "lightning" }, { id: 994, ja: "テツノコウベ", type: "darkness" },
  { id: 995, ja: "テツノドジン", type: "fighting" }, { id: 996, ja: "セビエ", type: "dragon" }, { id: 997, ja: "セゴール", type: "dragon" },
  { id: 998, ja: "セグレイブ", type: "dragon" }, { id: 999, ja: "コレクレー", type: "colorless" }, { id: 1000, ja: "サーフゴー", type: "metal" },
  { id: 1001, ja: "チオンジェン", type: "grass" }, { id: 1002, ja: "パオジアン", type: "water" }, { id: 1003, ja: "ディンルー", type: "fighting" },
  { id: 1004, ja: "イーユイ", type: "fire" }, { id: 1005, ja: "トドロクツキ", type: "darkness" }, { id: 1006, ja: "テツノブジン", type: "psychic" },
  { id: 1007, ja: "コライドン", type: "fighting" }, { id: 1008, ja: "ミライドン", type: "lightning" }, { id: 1009, ja: "ウネルミナモ", type: "water" },
  { id: 1010, ja: "テツノイサハ", type: "grass" }, { id: 1011, ja: "カミッチュ", type: "dragon" }, { id: 1012, ja: "チャデス", type: "grass" },
  { id: 1013, ja: "ヤバソチャ", type: "grass" }, { id: 1014, ja: "イイネイヌ", type: "psychic" }, { id: 1015, ja: "マシマシラ", type: "psychic" },
  { id: 1016, ja: "キチキギス", type: "psychic" }, { id: 1017, ja: "オーガポン", type: "grass" }, { id: 1018, ja: "ブリジュラス", type: "metal" },
  { id: 1019, ja: "カミツオロチ", type: "dragon" }, { id: 1020, ja: "ウガツホムラ", type: "fire" }, { id: 1021, ja: "タケルライコ", type: "dragon" },
  { id: 1022, ja: "テツノカシラ", type: "psychic" }, { id: 1023, ja: "テツノイワオ", type: "fighting" }, { id: 1024, ja: "テラパゴス", type: "colorless" },
  { id: 1025, ja: "モモワロウ", type: "psychic" },
];

export const POKEMON_DATA: PokemonEntry[] = [
  ...GEN1,
  ...GEN23,
  ...GEN45,
  ...GEN69,
];

export const getPokemonImageUrl = (id: number): string => {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
};

export const TYPE_COLORS: Record<string, string> = {
  grass: "#22c55e", fire: "#ef4444", water: "#3b82f6", lightning: "#eab308", psychic: "#a855f7",
  fighting: "#f97316", darkness: "#1f2937", metal: "#64748b", dragon: "#8b5cf6", colorless: "#94a3b8",
  fairy: "#ec4899", default: "#1f2937",
};
